id: IF455B365
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T06:27:24+00:00'
last_modified: '2022-06-08T16:45:12.532421+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG6120
  title: ཕྱི་རྒྱལ་གྱི་དམག་འཁྲུག་དང་གཡུལ་འཐབ་གྲགས་ཅན།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    '7384':
      image_group_id: I1KG8443
      title: ''
      total_pages: 314
      order: 1
      base_file: 7384.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
